### ISSUE TITLE
No Size Limit Needed

### ISSUE THREAD

**Issue by EillesWan** [phoenixr-codes/mcstructure#12]
Of course when we export the structure from _Minecraft_ there will be a size limit of 64*64 in x-z axis. However, while importing from a `.mcstructure` file, there will be no such limit. So adding such a limit to the function `__init__` of the class `structure` and that is certainly not necessary. I have tested on my PC and mobile device and proved that it(no import-to-game size limit) is true. If you want to add one, the better choice is to make it Optional. My suggestion is to add a argument `strict_checking: bool` which allows developers to further customize the settings.

当然游戏里导出方块有大小限制，可是导入没有！！！所以在这设限根本没必要。加一个参数叫 严格检查 可能更妥当一点，try try看吧。

**Comment by phoenixr-codes** [comment]
Changed with https://github.com/phoenixr-codes/mcstructure/commit/069e8fada44c537710f9950fe318279c545a19a6

Thanks for the research!
