### ISSUE TITLE
Suggested new alias

### ISSUE THREAD

**Issue by BryanValc** [phoenixr-codes/mcstructure#5]
![image](https://user-images.githubusercontent.com/71149864/228090251-bc01009f-5f85-4111-8e34-dd62ed780900.png)
It would be nice if there it was an alias for the dump method, an alias like save/write, it would be easier for many people to undersatand

**Comment by phoenixr-codes** [comment]
Most python libraries go with just `dump` like the json library or the third-party package tomli-w. It is now denoted how to save structures in the documentation:

https://mcstructure.readthedocs.io/en/latest/quickstart.html#saving-a-structure
